# Generated by Django 5.2.1 on 2025-06-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='kategoriýa')),
            ],
            options={
                'verbose_name': 'kategoriýa',
                'verbose_name_plural': 'kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='ölçeg birligi')),
            ],
            options={
                'verbose_name': 'ölçeg birligi',
                'verbose_name_plural': 'ölçeg birlikleri',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='harytyn ady')),
                ('sku', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='artikul')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='mukdary')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='baha')),
                ('description', models.TextField(blank=True, verbose_name='beýany')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='kategoriýa')),
                ('unit_of_measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.unitofmeasurement', verbose_name='ölçeg birligi')),
            ],
            options={
                'verbose_name': 'haryt',
                'verbose_name_plural': 'harytlar',
            },
        ),
    ]
