# Generated by Django 5.2.1 on 2025-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='images/avatar.png', null=True, upload_to='user_photos/'),
        ),
    ]
