# Generated by Django 5.2.1 on 2025-06-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='QR-код'),
        ),
    ]
