# Generated by Django 5.2.1 on 2025-06-03 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Müşderiniň ady')),
            ],
            options={
                'verbose_name': 'Müşderi',
                'verbose_name_plural': 'Müşderiler',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Sürüjiniň ady')),
            ],
            options={
                'verbose_name': 'Sürüji',
                'verbose_name_plural': 'Sürüjiler',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Üpjünçiniň ady')),
            ],
            options={
                'verbose_name': 'Üpjünçi',
                'verbose_name_plural': 'Üpjünçiler',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='sena pokupki'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='sena prodaji'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='sena optom'),
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faktura_type', models.PositiveSmallIntegerField(choices=[(1, 'Girdeji'), (2, 'Çykyjy'), (3, 'Wozwrat')], default=1, verbose_name='Faktura görnüşi')),
                ('description', models.TextField(blank=True, verbose_name='beýany')),
                ('date', models.DateTimeField(verbose_name='Senesi')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.client', verbose_name='Müşderi')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.driver', verbose_name=' sürüji')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.supplier', verbose_name=' üpjünçi')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Fakturalar',
            },
        ),
        migrations.CreateModel(
            name='FakturaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mukdary')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Baha')),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.faktura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
            options={
                'verbose_name': 'Faktura önümi',
                'verbose_name_plural': 'Faktura önümleri',
            },
        ),
    ]
