# Generated by Django 5.2.1 on 2025-06-25 07:49

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=store.models.product_image_path, verbose_name='Изображение'),
        ),
    ]
