# Generated by Django 5.2.1 on 2025-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_client_driver_supplier_remove_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Işgär',
                'verbose_name_plural': 'Işgärler',
            },
        ),
    ]
