# Generated by Django 5.2.1 on 2025-06-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='client',
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='fakturaproduct',
            name='faktura',
        ),
        migrations.RemoveField(
            model_name='fakturaproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Faktura',
        ),
        migrations.DeleteModel(
            name='FakturaProduct',
        ),
    ]
