# Generated by Django 5.2.1 on 2025-06-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agentler',
            },
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
