# Generated by Django 5.2.1 on 2025-06-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_faktura_client_remove_faktura_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Partneryn ady')),
                ('type', models.CharField(choices=[('klient', 'Alyjy (Покупатель)'), ('supplier', 'Üpjünçi (Поставщик)')], default='supplier', max_length=20, verbose_name='Partneriň görnüşi')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partnerler',
            },
        ),
    ]
