# Generated by Django 5.2.1 on 2025-06-18 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_agent_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.agent', verbose_name='Agent'),
        ),
    ]
