# Generated by Django 5.2.1 on 2025-06-23 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_partner_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measurement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.unitofmeasurement', verbose_name='esasy ölçeg birligi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='ady'),
        ),
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ady'),
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_conversions', to='store.unitofmeasurement')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_conversions', to='store.unitofmeasurement')),
            ],
            options={
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
