# Generated by Django 5.2.1 on 2025-06-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_freeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='firma_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Firma'),
        ),
    ]
