# Generated by Django 5.2.1 on 2025-06-30 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_firma_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('purchase', 'Цена закупки'), ('retail', 'Розничная цена'), ('wholesale', 'Оптовая цена'), ('discount', 'Цена со скидкой')], max_length=20, verbose_name='Тип цены')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Старая цена')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новая цена')),
                ('quantity_at_change', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество на складе')),
                ('difference', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Прибыль/Убыток')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='store.product')),
            ],
            options={
                'verbose_name': 'История изменения цены',
                'verbose_name_plural': 'История изменения цен',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['product', 'price_type'], name='store_price_product_fb9c26_idx')],
            },
        ),
    ]
