# Generated by Django 5.2.1 on 2025-06-23 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_category_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text='Сколько базовых единиц в 1 этой единице (напр: 1 банка = 18 литров → 18)', max_digits=10)),
                ('is_default_for_sale', models.BooleanField(default=False, help_text='Основная единица для продажи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='store.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.unitofmeasurement')),
            ],
            options={
                'verbose_name': 'ölçeg görnüşi',
                'verbose_name_plural': 'ölçeg görnüşleri',
                'unique_together': {('product', 'unit')},
            },
        ),
        migrations.DeleteModel(
            name='UnitConversion',
        ),
    ]
