# Generated by Django 5.2.1 on 2025-07-01 09:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_pricechangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Balans (deb/kred)'),
        ),
    ]
