# Generated by Django 5.2.1 on 2025-07-02 05:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_partner_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая сумма')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Отменена?')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_purchase_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Кем отменена')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('supplier', models.ForeignKey(limit_choices_to={'type__in': ['supplier', 'both']}, on_delete=django.db.models.deletion.PROTECT, to='store.partner', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Приходная накладная',
                'verbose_name_plural': 'Приходные накладные',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата возврата')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина возврата')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='store.purchaseinvoice', verbose_name='Исходная приходная накладная')),
            ],
            options={
                'verbose_name': 'Возврат по приходу',
                'verbose_name_plural': 'Возвраты по приходу',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Закупочная цена')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.purchasereturninvoice', verbose_name='Возврат по приходу')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция возврата по приходу',
                'verbose_name_plural': 'Позиции возврата по приходу',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая сумма')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Отменена?')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('buyer', models.ForeignKey(limit_choices_to={'type__in': ['klient', 'both']}, on_delete=django.db.models.deletion.PROTECT, to='store.partner', verbose_name='Покупатель')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_sales_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Кем отменена')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.employee', verbose_name='Доставил')),
            ],
            options={
                'verbose_name': 'Расходная накладная',
                'verbose_name_plural': 'Расходные накладные',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='store.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.salesreturninvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
    ]
